.PHONY: all sum interactive fileio exception quake clean

all: sum interactive fileio exception quake

sum:
	spim -file sum_array.asm

interactive:
	spim -file interactive_io.asm

fileio:
	spim -file file_io.asm

exception:
	spim -file exception_demo.asm

quake:
	spim -file quake_inv_sqrt.asm

clean:
	rm -f *.out
