.PHONY: all sum interactive fileio exception clean

all: sum interactive fileio exception

sum:
	spim -file sum_array.asm

interactive:
	spim -file interactive_io.asm

fileio:
	spim -file file_io.asm

exception:
	spim -file exception_demo.asm

clean:
	rm -f *.out
