import pytest
import asyncio
import os
import cv2
import numpy as np
import httpx

# In test_integration, we'll test the master's behavior when 0 workers are connected.
from main import app, UPLOAD_DIR_STR

@pytest.mark.asyncio
async def test_local_processing_fallback():
    # Create test image
    img = np.random.randint(0, 256, (100, 100), dtype=np.uint8)
    # Ensure some variation to see equalization change
    img[0:50, :] = 50 
    
    filename = "integration_test.jpg"
    file_path = os.path.join(UPLOAD_DIR_STR, filename)
    cv2.imwrite(file_path, img)
    
    # To trigger the fastapi background task processing during a test, we can use httpx.AsyncClient
    from httpx import ASGITransport
    async with httpx.AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        response = await client.post(f"/process/{filename}")
        assert response.status_code == 200
        assert "job_id" in response.json()
        
    # Yield control to the event loop so the BackgroundTask can run
    for _ in range(10):  # wait up to 1 second
        await asyncio.sleep(0.1)
        expected_out = os.path.join(UPLOAD_DIR_STR, "integration_test_equalized.jpg")
        if os.path.exists(expected_out):
            break
            
    assert os.path.exists(expected_out), "Equalized file was not generated by local fallback."
    
    # Clean up
    if os.path.exists(file_path):
        os.remove(file_path)
    if os.path.exists(expected_out):
        os.remove(expected_out)
